/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { UpgradeItem, Gem } from '../types';

export const INITIAL_UPGRADES: UpgradeItem[] = [
  {
    id: 'normal_pickaxe',
    name: 'ふつうの ピッケル ⛏️',
    description: '1タップで もらえる こうせきが 1こ ふえるよ！',
    emoji: '⛏️',
    cost: 10,
    baseCost: 10,
    level: 0,
    multiplier: 1,
    type: 'click',
  },
  {
    id: 'helper_robot',
    name: 'おてつだい ロボ 🤖',
    description: '1びょうごとに こうせきを 1こ じどうで ほってくれるよ！',
    emoji: '🤖',
    cost: 50,
    baseCost: 50,
    level: 0,
    multiplier: 1,
    type: 'auto',
  },
  {
    id: 'magic_pickaxe',
    name: 'まほうの ピッケル ✨',
    description: '1タップで もらえる こうせきが 5こ ふえるよ！',
    emoji: '✨',
    cost: 300,
    baseCost: 300,
    level: 0,
    multiplier: 5,
    type: 'click',
  },
  {
    id: 'dynamite',
    name: 'ダイナマイト 🧨',
    description: '1びょうごとに こうせきを 10こ じどうで ばくはつさせるよ！',
    emoji: '🧨',
    cost: 800,
    baseCost: 800,
    level: 0,
    multiplier: 10,
    type: 'auto',
  },
  {
    id: 'space_pickaxe',
    name: 'うちゅうの ピッケル 🚀',
    description: '1タップで もらえる こうせきが 50こ もふえるよ！',
    emoji: '🚀',
    cost: 3500,
    baseCost: 3500,
    level: 0,
    multiplier: 50,
    type: 'click',
  },
  {
    id: 'super_drill',
    name: 'スーパー ドリル 🌀',
    description: '1びょうごとに こうせきを 100こ じどうで ほりすすめるよ！',
    emoji: '🌀',
    cost: 10000,
    baseCost: 10000,
    level: 0,
    multiplier: 100,
    type: 'auto',
  },
];

export const INITIAL_GEMS: Gem[] = [
  {
    id: 'gem_ruby',
    name: 'もえる ルビー ❤️',
    description: 'まっかで もえる ほうせき。みるだけで げんきが でてくるよ！',
    emoji: '❤️',
    rarity: 'common',
    color: 'from-rose-400 to-red-600',
    unlocked: false,
    count: 0,
  },
  {
    id: 'gem_sapphire',
    name: 'ふかい サファイア 💙',
    description: 'うみの ように すきとおった あおい ほうせき。とっても クール！',
    emoji: '💙',
    rarity: 'common',
    color: 'from-blue-400 to-indigo-600',
    unlocked: false,
    count: 0,
  },
  {
    id: 'gem_emerald',
    name: 'もりの エメラルド 💚',
    description: 'みどりの かぜを かんじる ほうせき。やさしい きもちに なれるよ！',
    emoji: '💚',
    rarity: 'rare',
    color: 'from-emerald-400 to-teal-600',
    unlocked: false,
    count: 0,
  },
  {
    id: 'gem_topaz',
    name: 'きらきら トパーズ 💛',
    description: 'たいようの ひかりを あつめた きばいろの ほうせき。キラキラ！',
    emoji: '💛',
    rarity: 'rare',
    color: 'from-amber-300 to-yellow-500',
    unlocked: false,
    count: 0,
  },
  {
    id: 'gem_amethyst',
    name: 'ふしぎアメジスト 💜',
    description: 'まほうつかいが もっていそうな むらさきの ほうせき。あやしい かがやき！',
    emoji: '💜',
    rarity: 'rare',
    color: 'from-purple-400 to-violet-600',
    unlocked: false,
    count: 0,
  },
  {
    id: 'gem_rainbow_diamond',
    name: 'でんせつの ダイヤ 💎🌈',
    description: 'なないろに かがやく まぼろしの ダイヤ。もっていると しあわせに なれる！',
    emoji: '💎',
    rarity: 'legendary',
    color: 'from-pink-300 via-purple-300 to-cyan-300 text-transparent bg-clip-text animate-pulse',
    unlocked: false,
    count: 0,
  },
];
